export const environment = {
  production: true,
  VEHICLE_URL: "http://localhost:3000/api/v1/vehicle",

  VEHICLES_BRAND: ["ACURA", "AGRALE", "ALFA ROMEO", "AM GEN", "ASIA MOTORS", "ASTON MARTIN", "AUDI", "BABY", "BMW", "BRM", "BUGRE", "CADILLAC", "CBT JIPE", "CHANA", "CHANGAN", "CHERY", "CHEVROLET", "CHRYSLER", "CITROEN", "CROSS LANDER", "DAEWOO", "DAIHATSU", "DODGE", "EFFA", "ENGESA", "ENVEMO", "FERRARI", "FIAT", "FIBRAVAN", "FORD", "FOTON", "FYBER", "GEELY", "GREAT WALL", "GURGEL", "HAFEI", "HITECH ELECTRIC", "HONDA", "HYUNDAI", "ISUZU", "IVECO", "JAC", "JAGUAR", "JEEP", "JINBEI", "JPX", "KIA", "LADA", "LAMBORGHINI", "LAND ROVER", "LEXUS", "LIFAN", "LOBINI", "LOTUS", "MAHINDRA", "MASERATI", "MATRA", "MAZDA", "MCLAREN", "MERCEDES-BENZ", "MERCURY", "MG", "MINI", "MITSUBISHI", "MIURA", "NISSAN", "PEUGEOT", "PLYMOUTH", "PONTIAC", "PORSCHE", "RAM", "RELY", "RENAULT", "ROLLS-ROYCE", "ROVER", "SAAB", "SATURN", "SEAT", "SHINERAY", "SMART", "SSANGYONG", "SUBARU", "SUZUKI", "TAC", "TOYOTA", "TROLLER", "VOLKSWAGEN", "VOLVO", "WAKE", "WALK"]
};
